### ISSUE TITLE
Mask Image

### ISSUE THREAD

**Issue by Huaxingweichen** [belonel/cloth-virtual-try-on-using-stable-diffusion#1]
Hi, thanks for your great work.
I want to know how to generate the mask images for training.
Could you provide some tools or instructions?

**Comment by Huaxingweichen** [comment]
In my opinion, if I want to use your script to train my own model, I need to segment the cloth (instance image) first. I want to know whether it is a correct way to use your code. Thanks!

**Comment by belider** [comment]
Thanks for the comment. I used [u2net cloth-segmentation](https://github.com/levindabhi/cloth-segmentation) model to create masks for training. They have a handy collab. Just change the palette for black and white masks. I used this palette: [0, 0, 0, 255, 255, 255, 0, 0, 0, 255, 255, 255] to create upper body clothes masks.

**Comment by Huaxingweichen** [comment]
Thanks for your reply. I have already used the photoshop to create the mask.
I'm very interested in this topic. Thanks for you contribution for such a wonderful idea.

**Comment by Tourbillon** [comment]
@Huaxingweichen @belonel 
Hi, thanks for your great work.
I want to know what the input is. Is only the clothes with it's prompt or the people in the clothes with it's prompt?
