### ISSUE TITLE
Can you share more details about training&inferring?

### ISSUE THREAD

**Issue by ykk648** [belonel/cloth-virtual-try-on-using-stable-diffusion#3]
I can't reproduce the results shown in the README, so I want ask for some details.

For example, 
1. How many images did you use to train the Dreambooth inpaint model? Were both front views and other views used?
2. Did you use StableDiffusionInpaintPipeline in Diffusers to infer the trained model? What prompts did you use and were there any special parameters?

thx for your help.

**Comment by ykk648** [comment]
I thought I got what I wanted, thx

**Comment by kao2kao** [comment]
Can you share more details about inferring?

**Comment by ykk648** [comment]
> Can you share more details about inferring?

Use StableDiffusionInpaintPipeline, tune the params&prompts, try different kind of input images, do more tests, you will find the limit of DreamBooth.

**Comment by Tourbillon** [comment]
@ykk648 
Hi, thanks for your share.
I want to know what the input is. Is only the clothes with it's prompt or the people in the clothes with it's prompt? And can you leave your contact for me to share your test?

**Comment by ykk648** [comment]
@Tourbillon 
whole picture prompts, same as sd2.1 inpainting model using tricks

**Comment by Tourbillon** [comment]
@ykk648 
Thank you for your reply！
How many pictures are there for each prompt word？Did you reproduce the author's results？

**Comment by Tourbillon** [comment]
@ykk648 
One more question, during the training, did mask drop his clothes for training, and then when painting, did mask drop anthoer man's whole upper body?

**Comment by ykk648** [comment]
> @ykk648 Thank you for your reply！ How many pictures are there for each prompt word？Did you reproduce the author's results？

> @ykk648 One more question, during the training, did mask drop his clothes for training, and then when painting, did mask drop anthoer man's whole upper body?

如果说是作者那两张图，可以复现，在其他图片上效果一般
If you mean author's two pic results, it surely could reprode, but it may fail on other pics

mask是针对每张图片取的，无论是在training还是在infering，training时可以用随机mask（遵循diffusers官方做法）
Mask is for every pic itself, no matter training or infering stage, you can also try using random mask as the diffusers official practice.

**Comment by Tourbillon** [comment]
@ykk648 
我在twitter上关注了你，可以私聊一下么？我还是有些没有明白的地方

**Comment by ykk648** [comment]
@Tourbillon 最近在做NLP，不做sd相关了，不好意思

**Comment by Tourbillon** [comment]
@ykk648 
主要我没太明白这个输入，我看代码里要输入一张图像和一个图像的mask，我比较好奇的是，这个输入图像是那个黑人小哥穿着毛衣的图像，然后mask是这个衣服的mask，然后prompt比如是“一件黑色毛衣”这样么，然后这一个prompt可以对应两张黑人小哥的图像？然后，在inference的过程中，需要输入那个白人小哥的照片，然后mask掉他的上半身，然后使用提示词“一件黑色毛衣”通过生成模型生成衣服，整个过程是这样么？有点儿像是训练了一个lora模型的过程？

**Comment by Tourbillon** [comment]
@ykk648 
主要我没太明白这个输入，我看代码里要输入一张图像和一个图像的mask，我比较好奇的是，这个输入图像是那个黑人小哥穿着毛衣的图像，然后mask是这个衣服的mask，然后prompt比如是“一件黑色毛衣”这样么，然后这一个prompt可以对应两张黑人小哥的图像？然后，在inference的过程中，需要输入那个白人小哥的照片，然后mask掉他的上半身，然后使用提示词“一件黑色毛衣”通过生成模型生成衣服，整个过程是这样么？有点儿像是训练了一个lora模型的过程？

**Comment by ykk648** [comment]
@Tourbillon 
> 在inference的过程中，需要输入那个白人小哥的照片，然后mask掉他的上半身，然后使用提示词“一件黑色毛衣”通过生成模型生成衣服，

inpainting模型inpainting的时候是全图prompts，不是instance prompts, [参考](https://www.reddit.com/r/MachineLearning/comments/yaqlvi/rp_runway_stable_diffusion_inpainting_erase_and/) ，使用isntance prompts有时候也可以，两个实验我都做过

> 然后prompt比如是“一件黑色毛衣”这样么，然后这一个prompt可以对应两张黑人小哥的图像？

因为本repo作者用mask把instance分割出来才丢进去的，所以跟什么人没关系，这与[diffusers做法](
https://github.com/huggingface/diffusers/blob/c5933c9c89c9c23c5f7f0fcd532d9a7043d879b8/examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py#L58)不同，两个实验我都做过

> 有点儿像是训练了一个lora模型的过程？

sd的finetune方式：dreambooth lora hypernetwork TextualInversion

**Comment by Tourbillon** [comment]
多谢！我训练一下试试，我看最近新出的controlnet这种模型，不知道能不能保留生成的衣服的纹理信息

**Comment by Tourbillon** [comment]
@ykk648 
多谢！我训练一下试试，我看最近新出的controlnet这种模型，不知道能不能保留生成的衣服的纹理信息

**Comment by zihaolucky** [comment]
> @ykk648 多谢！我训练一下试试，我看最近新出的controlnet这种模型，不知道能不能保留生成的衣服的纹理信息

可能还要加canary之类的会好点；衣服上的复杂图案应该是不容易的

**Comment by ykk648** [comment]
https://github.com/xiezhy6/GP-VTON
https://github.com/miccunifi/ladi-vton
